FROM python:3.11-slim

# Системные зависимости + ffmpeg
RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg pkg-config \
    libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev \
    libavfilter-dev libswscale-dev libswresample-dev \
    && rm -rf /var/lib/apt/lists/*

# Опционально: фикс для питоновских локалей
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Код
COPY . .

# Запуск aiogram-поллинга
CMD ["python", "bot.py"]